apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: apache
    spec:
      volumes:
      - hostPath:
          path: /opt/Panorama
          type: ''
        name: appint
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-apache:latest
        name: apache
        ports:
        - containerPort: 80
        resources: {}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: '-agentpath:/opt/Panorama/hedzup/mn/lib/librpilj64.so'
          - name: RVBD_AGENT_FILES
            value: '1'
          - name: RVBD_AGENT_PORT
            value: '7073'
          - name: RVBD_DSAHOST
            valueFrom:
               fieldRef:
                   apiVersion: v1
                   fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /opt/Panorama
          name: appint
           
status: {}

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: catalog
    spec:
      volumes:
      - hostPath:
          path: /opt/Panorama
          type: ''
        name: appint
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-catalog:latest
        name: catalog
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: '-agentpath:/opt/Panorama/hedzup/mn/lib/librpilj64.so'
          - name: RVBD_AGENT_FILES
            value: '1'
          - name: RVBD_AGENT_PORT
            value: '7073'
          - name: RVBD_DSAHOST
            valueFrom:
               fieldRef:
                   apiVersion: v1
                   fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /opt/Panorama
          name: appint
status: {}

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: customer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: customer
    spec:
      volumes:
      - hostPath:
          path: /opt/Panorama
          type: ''
        name: appint
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-customer:latest
        name: customer
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: '-agentpath:/opt/Panorama/hedzup/mn/lib/librpilj64.so'
          - name: RVBD_AGENT_FILES
            value: '1'
          - name: RVBD_AGENT_PORT
            value: '7073'
          - name: RVBD_DSAHOST
            valueFrom:
               fieldRef:
                   apiVersion: v1
                   fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /opt/Panorama
          name: appint
status: {}

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      run: order
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: order
    spec:
      volumes:
      - hostPath:
          path: /opt/Panorama
          type: ''
        name: appint
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-order:latest
        name: order
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: '-agentpath:/opt/Panorama/hedzup/mn/lib/librpilj64.so'
          - name: RVBD_AGENT_FILES
            value: '1'
          - name: RVBD_AGENT_PORT
            value: '7073'
          - name: RVBD_DSAHOST
            valueFrom:
               fieldRef:
                   apiVersion: v1
                   fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /opt/Panorama
          name: appint
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: apache
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: catalog
  name: catalog
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: catalog
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: customer
  name: customer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: customer
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: order
  name: order
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: order
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: demo-apache-service
spec:
    rules:
    - host: micro.service-demo.com
      http:
          paths:
          - backend:
               serviceName: apache
               servicePort: 80
